from .pnl import load_data as pnl_load
from .maktab_royxat import load_data as maktab_royxat_load
from .maktab_kassa import load_data as maktab_kassa_load
from .stipendiya import load_data as stipendiya_load
from .maktab_xodimlar import load_data as maktab_xodimlar_load
from .pochemuchkadb import load_data as pochemuchkadb_load
from .dars_jadvali import load_data as darsjadvali_load
from .psixolog_test import load_data as psixolog_test_load
from .kutubxona import load_data as kutubxona_load
from .nps import load_data as nps_load
from .tugaraklar_reytingi import load_data as tugaraklar_reytingi_load
from .maktab_tadbirlar import load_data as maktab_tadbirlar_load