from .pnl import load_data as pnl_load
from .maktab_royxat import load_data as maktab_royxat_load
from .maktab_kassa import load_data as maktab_kassa_load
from .stipendiya import load_data as stipendiya_load
from .maktab_xodimlar import load_data as maktab_xodimlar_load
from .pochemuchkadb import load_data as pochemuchkadb_load
from .dars_jadvali import load_data as darsjadvali_load
from .psixolog_test import load_data as psixolog_test_load
from .kutubxona import load_data as kutubxona_load
from .nps import load_data as nps_load
from .tugaraklar_reytingi import load_data as tugaraklar_reytingi_load
from .maktab_tadbirlar import load_data as maktab_tadbirlar_load
from .dietolog import load_data as dietolog_load
from .new_pochemuchka import load_data as n_pochemuchka_load
from .new_kutubxona import load_data as n_kutubxona_load
from .shifokor_qabul import load_data as shifokor_qabul_load
from .adminstratsiya import load_data as adminstratsiya_load
from .psbaza import load_data as psbaza_load
from .materialniy_atchot import load_data as ma_load
from .printer_sheet import load_data as printer_load
from .avtobus import load_data as bus_load