from .pnl import extract_data as pnl_extract
from .maktab_royxat import extract_data as maktab_royxat_extract
from .maktab_kassa import extract_data as maktab_kassa_extract
from .stipendiya import extract_data as stipendiya_extract
from .maktab_xodimlar import extract_data as maktab_xodimlar_extract
from .pochemuchkadb import extract_data as pochemuchkadb_extract
from .dars_jadvali import extract_data as darsjadvali_extract
from .psixolog_test import extract_data as psixolog_test_extract
from .kutubxona import extract_data as kutubxona_extract
from .nps import extract_data as nps_extract
from .tugaraklar_reytingi import extract_data as tugaraklar_reytingi_extract
from .maktab_tadbirlar import extract_data as maktab_tadbirlar_extract
from .dietolog import extract_data as dietolog_extract
from .new_pochemuchka import extract_data as n_pochemuchka_extract
from .new_kutubxona import extract_data as n_kutubxona_extract
from .shifokor_qabul import extract_data as shifokor_qabul_extract
from .adminstratsiya import extract_data as adminstratsiya_extract
from .psbaza import extract_data as psbaza_extract
from .materialniy_atchot import extract_data as ma_extract
from .printer_sheet import extract_data as printer_extract
from .avtobus import extract_data as bus_extract